### ISSUE TITLE
请问tcp协议也是连结wss://danmuproxy.douyu.com:8506吗？

### ISSUE THREAD

**Issue by yoyosnart** [yjqiang/danmu#1]
如题 , python小白 , 使用了asyncore 连结wss://danmuproxy.douyu.com:8506 失败了

不知道是否是host不同的问题！

**Comment by yjqiang** [comment]
是的  我这边正常

**Comment by yjqiang** [comment]
详见 https://github.com/yjqiang/danmu/tree/master/examples/douyu

**Comment by yjqiang** [comment]
斗鱼应该改了协议了的

**Comment by yoyosnart** [comment]
谢谢大佬
