### ISSUE TITLE
弹幕工具异常捕获失败

### ISSUE THREAD

**Issue by falcomzwei** [yjqiang/danmu#4]
![a8cff75af4336f8ecf171423875c892](https://user-images.githubusercontent.com/12232972/82754992-5c5e5d00-9e03-11ea-9efd-75e611c19e73.png)
catch 异常失败导致的弹幕监控关闭，应该是导入的姿势引起的？
![image](https://user-images.githubusercontent.com/12232972/82755050-c6770200-9e03-11ea-8b5f-7741ee2b9022.png)
![image](https://user-images.githubusercontent.com/12232972/82755056-d4c51e00-9e03-11ea-8a21-3fcbe6dffbbb.png)

**Comment by yjqiang** [comment]
看起来像是bug
